[package]
name = "rhis"
version = "0.3.6"
authors = ["beltram.maldant <beltram.maldant@gmail.com>"]
edition = "2018"

[dependencies]
proxy-wasm = "0.1.0"
log = "0.4.8"
wasm-bindgen = "0.2.60"

[lib]
crate-type = ["cdylib"]